version: '3.8'
services:
  xss-two:
    image: athack-ctf/chall2025-xss-two:latest
    build: .
    hostname: xss-two
    ports:
    - 52053:2025
    deploy:
      resources:
        limits:
          cpus: '0.12'
          memory: 300m
